export enum Category {
  CONSUMABLE = "CONSUMABLE",
  DURABLE = "DURABLE",
  FIXED_ASSET = "FIXED_ASSET",
  BOOK = "BOOK",
}

export enum ItemStatus {
  AVAILABLE = "AVAILABLE",
  CHECKED_OUT = "CHECKED_OUT",
  DAMAGED = "DAMAGED",
  UNDER_REPAIR = "UNDER_REPAIR",
  LOST = "LOST",
  PENDING_MAINTENANCE = "PENDING_MAINTENANCE",
  DISPOSED = "DISPOSED",
}

export enum Role {
  ADMIN = "ADMIN",
  STAFF = "STAFF",
  INSTRUCTOR = "INSTRUCTOR",
}

export enum AdjustmentReason {
  LOST = "LOST",
  DAMAGED_PENDING_REPAIR = "DAMAGED_PENDING_REPAIR",
  COUNT_MISMATCH = "COUNT_MISMATCH",
  DISPOSAL = "DISPOSAL",
  OTHER = "OTHER",
}
